# Generated by Django 6.0.1 on 2026-02-07 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id_type', models.CharField(choices=[('GHANACARD', 'GhanaCard'), ('PASSPORT', 'Passport'), ('VOTERID', 'VoterID')], default='GHANACARD', max_length=20)),
                ('national_id_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('residential_address', models.CharField(help_text='Eg. AD-025-6434, Fawoade', max_length=255)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, help_text='Approximate monthly income (GHS)', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('TERMS_AND_CONDITIONS', 'Terms and Conditions'), ('DATA_PROCESSING', 'Data Processing'), ('CREDIT_BUREAU', 'Credit Bureau')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='customers.customer')),
            ],
            options={
                'unique_together': {('customer', 'consent_type', 'version')},
            },
        ),
    ]
