# Generated by Django 6.0.1 on 2026-02-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_employee'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('AUTO_APPROVED', 'Auto Approved'), ('MANUAL_APPROVED', 'Manual Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('justification', models.TextField(blank=True, help_text='Reason for manual decision or override')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='loans.loanapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Employee who manually reviewed the loan (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.employee')),
            ],
        ),
    ]
