# Generated by Django 6.0.1 on 2026-01-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('company_registration_number', models.CharField(help_text='Registered under the Companies Act, 2019 (Act 992)', max_length=100)),
                ('license_number', models.CharField(help_text='Issued by the Bank of Ghana', max_length=100, unique=True)),
                ('licensing_act', models.CharField(help_text='e.g. Act 930, Act 774, Act 987', max_length=50)),
                ('regulator', models.CharField(default='Bank of Ghana', editable=False, max_length=100)),
                ('license_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('institution_type', models.CharField(choices=[('BANK', 'Bank'), ('SDI', 'Specialised Deposit-Taking Institution'), ('MFI_TIER_2', 'Microfinance Institution (Tier 2)'), ('RCB', 'Rural & Community Bank'), ('NBFI', 'Non-Bank Financial Institution'), ('FINTECH', 'Fintech / Electronic Money Issuer')], max_length=20)),
                ('can_accept_deposits', models.BooleanField(default=False)),
                ('can_lend', models.BooleanField(default=True)),
                ('can_issue_e_money', models.BooleanField(default=False)),
                ('can_transmit_funds', models.BooleanField(default=False)),
                ('can_manage_investments', models.BooleanField(default=False)),
                ('minimum_required_capital', models.DecimalField(decimal_places=2, help_text='Regulatory minimum capital requirement', max_digits=20)),
                ('declared_paid_up_capital', models.DecimalField(decimal_places=2, help_text='Declared paid-up capital of the institution', max_digits=20)),
                ('capital_currency', models.CharField(default='GHS', max_length=10)),
                ('beneficial_ownership_disclosed', models.BooleanField(default=False)),
                ('fit_and_proper_compliant', models.BooleanField(default=False)),
                ('governance_framework_submitted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Only one FinancialInstitution may be active at any time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
